<?php
$this->openBoite("Recherche OAI");
?>
<center>
<form name="form" action="<?php echo BASE_URL ?>/opac/rechercheoai/resultat" method="post">
	<table width="100%">
		<tr>
			<td>
				<?php echo $this->_('Expression à rechercher') ?>&nbsp;<input type="text" name="expressionRecherche" value="<?php echo $this->expressionRecherche; ?>" size="35"
				onkeypress="if (event.keyCode == 13) {this.form.submit();return false;}">
				<input name="button" type="submit" class="submit" value="">
			</td>
			<td>
				<?php echo $this->_('Source') ?>&nbsp;
				<?php echo $this->formSelect("id_entrepot", $this->id_entrepot, "", $this->entrepots); ?>
			</td>
		</tr>
	</table>
</form>
</center>

<?php 
$this->closeBoite();

?>