<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_CSS?>recherche.css" />

<?php
echo $this->render("rechercheoai/index.phtml" );

if($this->erreur)
{
	echo '<p  class="error" align="center" style="margin-top:40px">'.$this->erreur.'</p>';
}
else
{
	if($this->nombre==1) 
    $texte=$this->_("1 notice trouvée"); 
  else 
    $texte=$this->_("%s notices trouvées", $this->nombre);
	echo BR.'<div class="liste_vignette">'.$texte.'</div>';
	foreach($this->notices as $notice) {
		echo '<div class="liste_vignette"><table width="100%">';
		echo '<tr><td align="right" style="width:10%" valign="top">Titre : </td><td><a href="'.$this->url(array('action' => 'viewnotice', 'id' => $notice->getId())).'" target="_blank">'.$notice->getTitre().'</a></td></tr>';

    $line_format = '<tr><td align="right"  valign="top">%s</td><td>%s</td></tr>';

		if ($notice->hasAuteur()) 
			printf($line_format, $this->_('Auteur :'), $notice->getAuteur());

		if ($notice->hasEditeur()) 
			printf($line_format, $this->_('Editeur :'), $notice->getEditeur());

		if($notice->hasDate()) 
			printf($line_format, $this->_('Publié en :'), $notice->getDate());

    printf($line_format, $this->_('Source :'), $notice->getLibelleEntrepot());
		echo '</table></div>';
	 }

	echo '<br/><div style="width:100%;text-align:center;">'.$this->pager($this->nombre,10,$this->page,$this->url_retour).'</div>';
}
?>