<h1><?php echo $this->notice->getTitre(); ?></h1>

<?php
foreach ($this->notice->getDataAsArray() as $label => $value)
	echo "<h3>".ucfirst($label)."</h3>$value";
?>


<?php if ($this->notice->getEntrepot()->isGallica()) {
    $id_ark = array_last(explode('/', $this->notice->getIdOai())); ?>

<h3><?php echo $this->_('Consultation') ?></h3>

<object
		classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" 
		width="640" 
		height="415" 
		codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">
	<param name="id" value="LecteurExportable" />
	<param name="allowScriptAccess" value="always" />
	<param name="wmode" value="window" />
	<param 
			name="FlashVars" 
			value="ark=<?php echo $id_ark ?>&amp;lang=fr&amp;mode=dp&amp;showArrows=1&amp;bgColor=8553603&amp;autoFlip=0&amp;startPage=71&amp;widthWidget=640&amp;heightWidget=415" />
	<param 
			name="src" 
			value="http://gallica.bnf.fr/flash/LecteurExportable.swf" />
	<embed 
			id="LecteurExportable" 
			type="application/x-shockwave-flash" 
			width="640" 
			height="415" 
			src="http://gallica.bnf.fr/flash/LecteurExportable.swf" 
			flashvars="ark=<?php echo $id_ark ?>&amp;lang=fr&amp;mode=dp&amp;showArrows=1&amp;bgColor=8553603&amp;autoFlip=0&amp;startPage=71&amp;widthWidget=640&amp;heightWidget=415" 
			allowscriptaccess="always" 
			wmode="window" />
</object>

<?php } ?>

