<?php
 echo $this->bouton('id=add_category',
										'picto=add.gif',
										'texte=' . $this->traduire('Ajouter une plage d\'ouverture'),
										'url=' . $this->url(array('action' => 'add',
																							'id' => null,
																							'site_id' => 1))
										);

 echo $this->tagModelTable($this->ouvertures, 

														 [$this->_('Jour'), 
															$this->_('Matin'), 
															$this->_(''), 
															$this->_('Après-midi'), 
															$this->_('')],

														 ['formatted_jour', 
															'debut_matin', 
															'fin_matin', 
															'debut_apres_midi', 
															'fin_apres_midi'],

														 [ ['action' => 'edit', 'content' => $this->boutonIco('type=edit')],
															 ['action' => 'delete', 'content' => $this->boutonIco('type=del')] ],
													 'ouvertures');
?>