<?php

echo $this->tagModelTable(
	$this->sites, 

	[$this->_('Libellé'), $this->_('Bibliothèque')],

	['libelle', 'libelle_bib'],

	[['action' => 'edit', 'content' => $this->boutonIco('type=edit')],
	 ['action' => 'browse', 'content' => $this->boutonIco('type=show')],
	 
	 function ($model) {
			if ($model->hasAdminUrl())
				return $this->tagAnchor($model->getAdminUrl(),
																URL_ADMIN_IMG.'picto/groupe_postes_16.png');

		}],

	'multimedia_location');

echo $this->subview;
?>