<link rel="stylesheet" type="text/css" href="<?php echo URL_JAVA ?>jcarousel/jcarousel.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL_JAVA ?>jcarousel/tango/skin.css">
<style>
	.jcarousel-skin-tango .jcarousel-container-horizontal
	{
    width: 85%;
		height:<?php echo $this->preferences["op_hauteur_img"]?>px;
    padding: 5px 35px 0px 30px;
	}
	.jcarousel-skin-tango .jcarousel-item
	{
    width:<?php echo $this->preferences["op_largeur_img"]?>px;
    height: <?php echo $this->preferences["op_hauteur_img"]+5 ?>px;
		margin-left:3px;
	}
</style>

<script src="<?php echo JQUERY ?>" type="text/javascript"> </script>
<script type="text/javascript" src="<?php echo URL_JAVA ?>jcarousel/jcarousel.pack.js"></script>
<script type="text/javascript">

function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel({
        auto: <?php echo $this->preferences["op_auto"]?>,
        wrap: 'last',
				scroll: <?php echo $this->preferences["op_scroll"]?>,
        initCallback: mycarousel_initCallback
    });
});
</script>

<center>


<?php
if(!$this->notices) echo '<p style="margin-left:10px;color:red;font-size:10pt">Aucun document n\'a été trouvé.</p>';
else
{
	echo '<ul id="mycarousel" class="jcarousel-skin-tango">';
	foreach($this->notices as $notice)
	{
		echo '<li>';
		echo '<a href="'.BASE_URL.'/recherche/viewnotice/id/'.$notice["id_notice"].'/type_doc/'.$notice["type_doc"].'" target="_parent">';
		echo '<img src="'.$notice["vignette"].'" title="'.$notice["titre"].'" width="'.$this->preferences["op_largeur_img"].'" height="'.$this->preferences["op_hauteur_img"].'" style="border:1px solid #B0BEC7"';
		echo '</a>';
		echo '</li>';
	}
	echo '</ul>';
}
?>

</center>


