<link rel="stylesheet" href="<?php echo URL_JAVA?>slide_show/image-slideshow.css" type="text/css">
<script src="<?php echo URL_JAVA; ?>slide_show/image-slideshow.js" type="text/javascript"> </script>

<?php
// Proprietes
$largeur=$this->preferences["op_largeur_img"];
$hauteur=$this->preferences["op_hauteur_img"];
if(!$largeur) $largeur=90;
if(!$hauteur) $hauteur=110;

if(!$this->notices) $images='<p style="margin-left:10px;color:red;font-size:10pt">'.$this->_("Aucun document n'a été trouvé").'</p>';
else
{
	foreach($this->notices as $notice)
	{
		$img='<img alt="vignette notice'.$notice["titre"].'" src="'.$notice["vignette"].'" width="'.$largeur.'" height="'.$hauteur.'" style="float:left;" alt="'.$notice["titre"].'" title="'.$notice["titre"].'"/>';
		$images.= '<a id="test" href="'.BASE_URL.'/recherche/viewnotice/id/'.$notice["id_notice"].'/type_doc/'.$notice["type_doc"].'" target="_parent">'.$img.'</a> ';		
	}
}
?>

<div id="dhtmlgoodies_slideshow" style="width:100%;">
	<div id="galleryContainer" style="height:<?php echo $hauteur+2 ?>px;overflow:hidden;padding:1px;position:relative;">
		<div id="arrow_left"><img alt='<?php echo $this->_('défilement à gauche') ?>' src="<?php echo URL_JAVA ?>slide_show/arrow_left.gif" height="<?php echo $hauteur ?>" style="cursor:pointer;"></div>
		<div id="arrow_right"><img alt='<?php echo $this->_('défilement à droite') ?>' src="<?php echo URL_JAVA ?>slide_show/arrow_right.gif" height="<?php echo $hauteur ?>" style="cursor:pointer;"></div>
		<div id="theImages"> <?php echo $images ?>
			<div id="slideEnd"></div>
		</div>
	</div>
</div>

