<div>
	 <h2><?php echo $this->formation->getLibelle() ?></h2>
	 <div><?php echo $this->formation->getDescription() ?></div>


	<table class="lieux">
	<thead>
		<tr class="soustitre">
			<td>Date</td>
			<td>Lieu</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
  <tbody>
	 <?php
	    echo $this->partialCycle('abonne/_session.phtml',
															 'session',
															 $this->formation->getSessions(),
															 array('first', 'second'));
	  ?>
	</tbody>
  </table>
</div>