<tr class="session_<?php echo $this->session->getId()?> <?php echo $this->item_class ?>">
<?php 
echo sprintf("<td>%s %s</td>", 
						 $this->humanDate($this->session->getDateDebut(), 'dd MMMM Y'),
						 $this->session->isAnnule() ? '(Annulé)' : '');
echo sprintf("<td>%s&nbsp;</td>", $this->session->getLibelleLieu());
echo sprintf("<td>%s</td>", 
						 $this->tagAnchor(array('action' => 'detail_session',
																		'id' => $this->session->getId()),
															$this->_('Détails de la session')));
echo sprintf("<td>%s</td>",
						 $this->tagSessionFormationInscription($this->session)); 
?>
</tr>