<?php
$this->openBoite($this->_("Votre fiche"));

echo $this->abonne_AccesFiche($this->user);
echo $this->abonne_Abonnement($this->user);
echo $this->abonne_Prets($this->user);
echo $this->abonne_Reservations($this->user);
echo $this->abonne_Paniers($this->user);
echo $this->abonne_Newsletters($this->user);
echo $this->abonne_Formations($this->user);
echo $this->abonne_Multimedia($this->user);

if ($this->error) 
	echo sprintf('<div class="error">%s</div>', $this->error);

$this->closeBoite();
?>