<ul>
	<li><?php echo sprintf('%s : %s', $this->_('Lieu'), $this->escape($this->location));?></li>
	<li><?php echo sprintf('%s : %s', $this->_('Jour'), $this->escape($this->day));?></li>
	<li><?php echo sprintf('%s : %s', $this->_('À partir de'), $this->escape($this->time));?></li>
	<li><?php echo sprintf('%s : %s', $this->_('Durée'), $this->escape($this->duration));?></li>
	<li><?php echo sprintf('%s : %s', $this->_('Poste'), $this->escape($this->device));?></li>
</ul>