<?php $this->openBoite($this->_("Réserver un poste multimédia")); ?>
<?php echo $this->timeline($this->timelineActions);?>

<div class="multimedia_reservation">
		<h2><?php echo $this->_('Ma réservation');?></h2>
		<ul>
			<li><?php echo sprintf('%s : %s', $this->_('Lieu'), $this->escape($this->location));?></li>
			<li><?php echo sprintf('%s : %s', $this->_('Jour'), $this->escape($this->day));?></li>
			<li><?php echo sprintf('%s : %s', $this->_('À partir de'), $this->escape($this->time));?></li>
			<li><?php echo sprintf('%s : %s', $this->_('Durée'), $this->escape($this->duration));?></li>
			<li><?php echo sprintf('%s : %s', $this->_('Poste'), $this->escape($this->device));?></li>
		</ul>

		<?php echo $this->tagAnchor(array('validate' => 1), $this->_('Confirmer'));?>
</div>
<?php $this->closeBoite();?>