<?php
echo $this->bouton('id=add',
									 'picto=add.gif',
									 'texte=' . $this->_('Déclarer un nouveau lieu'),
									 'url=' . $this->url(array('action' => 'add',
																						 'id' => null))
									 );
?>

<ul class="tree">
<?php
	 echo $this->partialCycle('lieu/_lieu.phtml',
														'lieu',
														$this->lieux,
														array('first', 'second'));
?>
</ul>