<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US" xml:lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
	<?php
		if (trim($this->nomSite)) echo $this->nomSite;
		else echo DEFAULT_TITLE_ADMIN;
	?>
</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<link rel="apple-touch-icon" href="<?php echo URL_IMG ?>apple-touch-icon.png" />
<meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
<meta name="description" content="<?php echo $this->ref_description;?>"/>
<meta name="keywords" content="<?php echo $this->ref_tags;?>"/>
<meta content="all" name="robots"/>
<meta content="3 days" name="revisit-after"/>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_CSS?>global.css"/>

<?php if ($this->profil->hasHeaderCss()) {?>
   <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->profil->getHeaderCss() ?>" />
<?php } ?>


<script src="<?php echo JQUERY?>" type="text/javascript"> </script>
<script type="text/javascript" language="javascript">
	<?php  echo("var baseUrl = \"" . BASE_URL . "\";");?>
	<?php  echo("var imagesUrl = \"" . URL_IMG . "\";");?>
	<?php  echo("var cssUrl = \"" . URL_CSS . "\";");?>
	<?php  echo("var userFilesUrl = \"" . USERFILESURL . "\";");?>
	<?php  echo("var idAbon = \"" . $this->session->idAbon . "\";");?>
</script>
<script src="<?php echo URL_JS?>global.js" type="text/javascript"> </script>

</head>