<!DOCTYPE html >
<html lang="<?php echo $this->_translate()->getLocale() ?>">
<head>
	 <title><?php echo $this->getTitre() ?></title>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<link rel="apple-touch-icon" href="<?php echo URL_IMG ?>apple-touch-icon.png" />
<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="<?php echo $this->ref_description;?>"/>
<meta name="keywords" content="<?php echo $this->ref_tags;?>"/>
<meta content="all" name="robots"/>
<meta content="3 days" name="revisit-after"/>

<?php

$head_scripts = Class_ScriptLoader::newInstance()
	 ->loadJQuery()
	 ->loadJQueryMobile()
	 ->addSkinStyleSheet('global');

if ($this->profil->hasHeaderCss())
	$head_scripts->addStyleSheeet($this->header_css);

$script_loader = Class_ScriptLoader::getInstance();	 

$head_scripts->renderStyleSheets();
$script_loader->renderStyleSheets();

$head_scripts->renderJavaScripts();
$script_loader->renderJavaScripts();
?>

</head>