<?php
ob_start();
?>

<body class="main" <?php echo $this->bodyParam; ?>>
	<img src="<?php  echo $this->profil->getHeaderImg(); ?>" style="width:100%" alt="<?php echo $this->_('Bannière') ?>">
			<div class="main" data-role="page">
				<?php 
					echo $this->render($this->actionScript);
				?>
		</div>
<?php echo $this->render('footer.phtml'); ?>

<?php
$html = ob_get_contents();
ob_end_clean();

echo $this->render('head.phtml');
echo $html;
?>