<?php
  $url_edit_members = $this->url(array('action' => 'editmembers',
																			 'id' => $this->group->getId()));

  $url_edit_group = $this->url(array('action' => 'edit',
																		 'id' => $this->group->getId()));
?>
<tr class="<?php echo $this->item_class;?>">
	<td><?php echo $this->tagAnchor($url_edit_group, $this->group->getLibelle());?></td>
	<td><?php echo $this->tagAnchor($url_edit_members, $this->group->numberOfUsers());?></td>
	<?php if (Class_AdminVar::isFormationEnabled()) { ?>
	<td><?php echo $this->tagAnchor($url_edit_group, implode(', ', $this->group->getRightsLibelles()));?></td>
  <?php } ?>
	<td><?php
  echo sprintf('%s %s %s', 
							 $this->tagAnchor($url_edit_group,
																$this->boutonIco("type=edit")),

							 $this->tagAnchor($url_edit_members,
																$this->boutonIco("picto=picto/abonnes.gif", "bulle=Membres")),

							 $this->tagAnchor($this->url(array('action' => 'delete',
																								 'id' => $this->group->getId())),
																$this->boutonIco("type=del")));
  ?>
	</td>
</tr>
