<?php echo $this->toolbar($this->categorie->getLibelle(), $this->url(array(), null, true) ,false); ?>

<ul data-role="listview">
	<li data-role="list-divider"><?php echo $this->categorie->getLibelle();?></li>
	<?php foreach($this->albums as $album) { ?>
		<li><?php echo $this->tagAnchor($this->url(array('action' => 'view-album', 
																										 'id' => $album->getId())),
																		$album->getTitre());?></li>
	<?php } ?>
</ul>
