<?php echo $this->toolbar($this->categorie->getLibelle(), $this->url(array(), null, true) ,false); ?>
<div class="liste">
	 <ul>

	 <?php 

	 foreach($this->albums as $album) {
		 echo sprintf('<li class="lien">%s</li>',
									$this->tagAnchor(
																	 $this->url(array('action' => 'view-album', 
																										'id' => $album->getId())),
																	 $album->getTitre()
																	 ));
	 }

	 ?>
	 </ul>
</div>
