<center>
	<h1>Propriétés du module Deux colonnes</h1><br>
	<div class="formTable">
		<form class="news" method="post" action="<?php echo $this->url ?>">

			<fieldset>
				<legend>Affichage</legend>
				<table cellspacing="2">

					<tr>
						<td class="droite">Style de boite&nbsp;</td>
						<td class="gauche"><?php echo $this->combo_templates ?></td>
					</tr>

				</table>
			</fieldset>
			<br>

			<fieldset>
				<legend>Généralités</legend>
				<table cellspacing="2">
					<tr>
						<td class="droite">Titre&nbsp;</td>
						<td class="gauche">
							<input type="text" name="titre" size="55" value='<?php print htmlspecialchars($this->preferences["titre"], ENT_QUOTES) ?>' >
						</td>
					</tr>
				</table>
			</fieldset>
			<br>

			<fieldset>
				<legend>Colonnes</legend>
				<table cellspacing="2">
					<tr>
						<td class="droite">Module à gauche</td>
						<td class="gauche">
							<?php echo $this->formSelect("col_gauche_type",
																					 $this->preferences["col_gauche_type"],
																					 "", $this->modules) ?>
						</td>
					</tr>
					<tr>
						<td class="droite">Module à droite</td>
						<td class="gauche">
							<?php echo $this->formSelect("col_droite_type",
																					 $this->preferences["col_droite_type"],
																					 "", $this->modules) ?>
						</td>
					</tr>
				</table>
			</fieldset>
			<br>

			<?php echo $this->formSubmit("Valider","Valider",array("class" => "bouton")) ?>
		</form>
	</div>
</center>
