<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_ADMIN_JS?>jquery_ui/css/jquery.ui.all.css" />
<script src="<?php echo JQUERY; ?>" type="text/javascript"> </script>
<script src="<?php echo URL_ADMIN_JS; ?>jquery_ui/jquery.ui.core.min.js" type="text/javascript"> </script>
<script src="<?php echo URL_ADMIN_JS; ?>jquery_ui/jquery.ui.widget.min.js" type="text/javascript"> </script>
<script src="<?php echo URL_ADMIN_JS; ?>jquery_ui/jquery.ui.mouse.min.js" type="text/javascript"> </script>
<script src="<?php echo URL_ADMIN_JS; ?>jquery_ui/jquery.ui.slider.min.js" type="text/javascript"> </script>

<center>
<h1>Propriétés de la boîte de recherche simple</h1><br>
<div class="formTable">
	<form method="post" action="<?php echo $this->url ?>">
			
			<fieldset>
			<legend>Affichage</legend>
			<table cellspacing="2">
    		
    		<tr>
    			<td class="droite">Style de boite&nbsp;</td>
    			<td class="gauche"><?php echo $this->combo_templates ?></td>
    		</tr>

				<tr>
    			<td class="droite">Largeur du champ de saisie&nbsp;</td>
    			<td class="gauche"><?php echo $this->tagSlider("largeur",$this->preferences["largeur"],100,300,1) ?></td>
    		</tr>
    		
  		</table>
			</fieldset>
			<br>
			
			<fieldset>
			<legend>Généralités</legend>
			<table cellspacing="2">
    		
    		<tr>
    			<td class="droite">Titre&nbsp;</td>
    			<td class="gauche"><input type="text" name="titre" size="55" value="<?php print($this->preferences["titre"]); ?>"></td>
    		</tr>
    		
    		<tr>
					<td class="droite">Proposer la sélection de bibliothèques&nbsp;</td>
					<td class="gauche"><?php echo $this->formSelect("select_bib",$this->preferences["select_bib"],"",array("1" => "oui","0"=>"non")) ?></td>
				</tr>

				<?php
						if($this->ya_annexes)
						{
							echo '<tr>';
							echo '<td class="droite">Proposer la sélection de sites</td>';
							echo '<td class="gauche">'.$this->formSelect("select_annexe",$this->preferences["select_annexe"],"",array("1" => "oui","0"=>"non")).'</td>';
							echo '</tr>';
						}
				?>

				<tr>
					<td class="droite">Proposer la sélection de types de docs&nbsp;</td>
					<td class="gauche"><?php echo $this->formSelect("select_doc",$this->preferences["select_doc"],"",array("1" => "oui","0"=>"non")) ?></td>
				</tr>

    		<tr>
    			<td class="droite">Message au-dessus du champ de saisie&nbsp;</td>
    			<td class="gauche"><input type="text" name="message" size="55" value="<?php print($this->preferences["message"]); ?>"></td>
    		</tr>
    		
    		<tr>
    			<td class="droite">Message exemple de recherche&nbsp;</td>
    			<td class="gauche"><input type="text" name="exemple" size="55" value="<?php print($this->preferences["exemple"]); ?>"></td>
    		</tr>

				<tr>
					<td class="droite">Afficher le lien recherche avancée&nbsp;</td>
					<td class="gauche">
						<?php $checked = $this->preferences["recherche_avancee"] == 'on' ? "checked='checked'" : ""; ?>
						<input type="checkbox" name="recherche_avancee" <?php echo $checked?>>
					</td>
				</tr>
    		
  		</table>
			</fieldset>

			<br>
			<fieldset>
			<legend>Filtres</legend>
			<table cellspacing="2">

    		<tr>
    			<td class="droite">Type de document&nbsp;</td>
    			<td class="gauche"><?php echo Class_Codification::getComboTypesDocs($this->preferences["type_doc"],"",true) ?></td>
    		</tr>

  		</table>
			</fieldset>
				
		<?php echo $this->formSubmit("Valider","Valider",array("class" => "bouton")) ?>
 	</form>
 </div>
