<?php 
echo '<script src="'.URL_ADMIN_JS.'drag_and_drop.js'.'" type="text/javascript"> </script>';
echo '<script src="'.URL_ADMIN_JS.'selection_champs.js'.'" type="text/javascript"> </script>';
echo '<link rel="stylesheet" type="text/css" media="screen" href="'.URL_ADMIN_CSS.'drag_and_drop.css" />';
echo $this->tagSelectionChamps("libelles");

?>
<center>
<h1>Propriétés d'affichage du nuage de tags</h1><br>
<div class="formTable">
	<form method="post" action="<?php echo $this->url ?>">
		
			<fieldset>
			<legend>Affichage</legend>
			<table cellspacing="2">
				
				<tr>
					<td class="droite">Style de boite&nbsp;</td>
					<td class="gauche"><?php echo $this->combo_templates ?></td>
				</tr>
				
			</table>
			</fieldset>
			<br>
			
			<fieldset>
			<legend>Généralités</legend>
			<table cellspacing="2">
				<tr>
					<td class="droite">Titre&nbsp;</td>
					<td class="gauche"><input type="text" name="message" size="52" value="<?php print($this->preferences["message"]); ?>"></td>
				</tr>
				<tr>
					<td class="droite" valign="top">Types de notices&nbsp;</td>
					<td class="gauche">
    	      <?php 
              echo $this->formSelect("notices",
                                     $this->preferences["notices"],
                                     "",
                                     array("0" => "Toutes",
                                           "1" => "Les nouveautés",
                                           "2" => "Les plus consultées"));
            ?>
					</td>
				</tr>
				<td class="droite" valign="top">Types de tags&nbsp;</td>
				<?php 
						$data=$this->tagSelectionChamps("type_tags",$this->preferences["type_tags"]); echo $data["codes_dispo"];
						echo '<td class="gauche">';						
						echo $data["champ_code"].$data["champ_libelle"].$data["bloc_saisie"];
						?> 
					</td>
				</tr>
				<tr>
					<td class="droite">Catalogue&nbsp;</td>
					<td class="gauche">
							 <?php echo $this->formSelect("id_catalogue",
																						 $this->preferences["id_catalogue"],
																						 null,
																						 $this->catalogues) ?>
					</td>
				</tr>
			</table>
			</fieldset>
		
		<br>
			<fieldset>
			<legend>Limites</legend>
			<table cellspacing="2">
				<tr>
					<td class="droite">Nombre de notices à analyser&nbsp;</td>
					<td class="gauche"><input type="text" name="limite" size="4" value="<?php print($this->preferences["limite"]); ?>"></td>
				</tr>
				<tr>
					<td class="droite">Nombre de tags à afficher dans le nuage&nbsp;</td>
					<td class="gauche"><input type="text" name="nombre" size="4" value="<?php print($this->preferences["nombre"]); ?>"></td>
				</tr>
			</table>
			</fieldset>
		<?php echo $this->formSubmit("Valider","Valider",array("class" => "bouton")) ?>
	</form>
 </div>
