<?php
echo $this->toolbar($this->_("Avis"));
echo '<h1>'.$this->notice->getTitrePrincipal().'</h1>';

$avis_bib = $this->notice->getAvisBibliothecaire();
$avis_abon = $this->notice->getAvisAbonne();
?>


<ul data-role="listview" data-inset="true">
  <li date-theme="c">
  <?php 
  echo $this->resumeAvis($this->_('Bibliothécaires'), $avis_bib);
  echo $this->resumeAvis($this->_('Lecteurs du portail'), $avis_abon);?>
  </li>
  
  <li date-theme="c" data-role="list-divider">
    <?php echo $this->_('Avis des bibliothécaires');?>
  </li>
  <?php foreach ($avis_bib as $avis) { ?>
    <li><?php echo $this->enteteAvis($avis);?></li>
  <?php } ?>
<?php  if (empty($avis_bib)) { ?>
<li><?php echo 'Aucun commentaire';?></li>
<?php } ?>

  <li date-theme="c" data-role="list-divider">
    <?php echo $this->_('Avis des lecteurs');?>
  </li>
  <?php foreach ($avis_abon as $avis) { ?>
    <li><?php echo $this->enteteAvis($avis);?></li>
  <?php } ?>
<?php  if (empty($avis_abon)) { ?>
<li><?php echo 'Aucun commentaire';?></li>
<?php } ?>
</ul>
