<?php
echo $this->toolbar("Avis", array('action' => 'viewnotice'), true);
echo '<h1>'.$this->notice->getTitrePrincipal().'</h1>';

$avis_bib = $this->notice->getAvisBibliothecaire();
$avis_abon = $this->notice->getAvisAbonne();
?>


<div class="pave">
	<?php 
	echo $this->resumeAvis($this->_('Bibliothécaires'), $avis_bib);

	echo $this->resumeAvis($this->_('Lecteurs du portail'), $avis_abon);
  ?>
</div>


<div class="pave">
		<?php 
		echo '<div>'.$this->_('Avis des bibliothécaires').'</div>';
		foreach ($avis_bib as $avis) 
			echo '<div class="fonction">'.$this->enteteAvis($avis).'</div>';	
    ?>
</div>


<div class="pave">
		<?php 
		echo '<div>'.$this->_('Avis des lecteurs').'</div>';
    foreach ($avis_abon as $avis) echo $this->enteteAvis($avis);	
    ?>
</div>