<?php
echo $this->toolbar($this->_("Exemplaires"), 
										array('action' => 'viewnotice'), 
										false);
?>
<h1><?php echo $this->escape($this->notice->getTitrePrincipal());?></h1>
<?php 
if (0 == count($exemplaires = $this->notice->getExemplaires())) 
	echo $this->_('Aucun exemplaire.');

$num = 0;
foreach ($exemplaires as $exemplaire) { ?>
<div class="pave">
	<table>
		<tr><td colspan="2"><strong><?php echo $this->_('n°') . ' ' . ++$num;?></strong></td></tr>
		<tr>
			<td align="right"><?php echo $this->_('Bibliothèque');?> : </td>
			<td><?php echo $this->escape($exemplaire->getBib()->getLibelle());?></td>
		</tr>
		<?php if ($cote = $exemplaire->getCote()) { ?>
		<tr>
			<td align="right"><?php echo $this->_('Cote');?> : </td>
			<td><?php echo $this->escape($cote);?></td>
		</tr>
		<?php	} ?>
		<tr>
			<td align="right"><?php echo $this->_('Disponibilité');?> : </td>
			<td>non connue</td>
		</tr>
	</table>
</div>
<?php	} ?>
