<?php
echo $this->toolbar($this->_("Exemplaires"), 
										array('action' => 'viewnotice'), 
										false);
?>
<h1><?php echo $this->escape($this->notice->getTitrePrincipal());?></h1>
<?php 
if (0 == count($exemplaires = $this->notice->getExemplaires())) 
	echo $this->_('Aucun exemplaire.');

$num = 0;
foreach ($exemplaires as $exemplaire) {
  $sigb_exemplaire = $exemplaire->getSigbExemplaire();
?>
<div class="pave">
	<table>
		<tr><td colspan="2"><strong><?php echo $this->_('n°') . ' ' . ++$num;?></strong></td></tr>
		<tr>
			<td align="right"><?php echo $this->_('Bibliothèque');?> : </td>
			<td><?php echo $this->escape($exemplaire->getBib()->getLibelle());?></td>
		</tr>
		<?php if ($cote = $exemplaire->getCote()) { ?>
		<tr>
			<td align="right"><?php echo $this->_('Cote');?> : </td>
			<td><?php echo $this->escape($cote);?></td>
		</tr>
		<?php	} ?>
		<tr>
			<td align="right"><?php echo $this->_('Disponibilité');?> : </td>
			<td><?php 
				echo ($sigb_exemplaire) ? $sigb_exemplaire->getDisponibilite() : $this->_('non connue');
			?></td>
		</tr>
	</table>
	<?php 
	if (Class_AdminVar::isPackMobileEnabled()
			&& (!$exemplaire->getBib()->getInterdireResa())
			&& $sigb_exemplaire
			&& $sigb_exemplaire->isReservable()) { 
	?>
	<div class="fonction">
		<a href="<?php 
			echo $this->url(array('controller' => 'recherche',
			                      'action' => 'reservation',
														'b' => $exemplaire->getBib()->getId(),
														'e' => $exemplaire->getId(),
														'a' => $sigb_exemplaire->getCodeAnnexe()), 
										 null, true);
		?>" style="display:block;" data-ajax="false" rel="external"><?php echo $this->_('Réserver');?></a>
	</div>
	<?php	} ?>
</div>
<?php	} ?>
