<?php
echo $this->toolbar($this->_("Jaquette"), 
										array('action' => 'viewnotice'), 
										true);

echo '<h1>'.$this->notice->getTitrePrincipal().'</h1>';
echo '<div class="pave" align="center">';
echo sprintf('<a href="%s"><img class="grande_image" src="%s"></a>',
						 $this->url(array('action' => 'viewnotice')),
						 $this->notice->getUrlVignette());
echo '</div>'.BR;
?>
