<?php 
echo $this->toolbar($this->_("Recherche"), 
		    array('action' => 'simple')); ?>

<ul data-role="listview" data-inset="true">
  <li data-theme="c">
    <img src="<?php echo $this->notice->getUrlVignette();?>">
    <h3><?php echo $this->iconeSupport($this->notice->getTypeDoc()) . $this->notice->getTitrePrincipal() ;?></h3>
    <p><?php echo $this->notice->getAuteurPrincipal();?></p>
    <p><?php if ($annee = $this->notice->getAnnee())
      echo $this->_('Année')," : ", $annee;?></p>
    <p><?php if ($editeur = $this->notice->getEditeur())
      echo $this->_('Editeur(s)')," : ", $editeur;?></p>
  </li>
<?php foreach ($this->actions as $libelle => $action) { ?>
	<li><?php echo  $this->tagAnchor(array('action' => $action['action']),
					  $libelle,
					  isset($action['attribs']) ? $action['attribs'] : array());?>
	</li>
<?php } ?>
</ul>

<?php 

?>