<?php echo $this->toolbar("Recherche", $this->url(array('action' => 'simple')), false); ?>

<div class="pave">
	 <div class="entete_notice">

	 <?php 
	 echo $this->iconeSupport($this->notice->getTypeDoc());
	 echo sprintf('<a href="%s"><img src="%s" alt="%s"/></a>',
								$this->url(array('action' => 'grandeimage')),
								$this->notice->getUrlVignette(),
								$this->_('Vignette'));
	 echo '<h1>'.$this->notice->getTitrePrincipal().'</h1>'; 
	 echo '<h1>'.$this->notice->getAuteurPrincipal().'</h1>'; 

   if ($editeur = $this->notice->getEditeur())
		 echo sprintf('<div>%s : %s</div>', $this->_('Editeur(s)'), $editeur);

   if ($annee = $this->notice->getAnnee())
		 echo sprintf('<div>%s : %s</div>', $this->_('Année'), $annee);
   ?>
   <div class="clear"></div>
   </div>

<?php
foreach ($this->actions as $libelle => $action) {
	echo sprintf('<a href="%s"><div class="fonction">%s</div></a>',
							 $this->url($action),
							 $libelle);
}

?>
</div>
