<tr class="<?php echo $this->item_class ?>">
	<td><?php echo htmlentities($this->newsletter->getTitre(), ENT_QUOTES, 'UTF-8'); ?></td>
	<td><?php 
			if (null == $last_date = $this->newsletter->getLastDistributionDate())
				echo 'Aucune';
			else
				echo date('d/m/Y H:i', strtotime($last_date)); 
		?></td>

	 <?php 
			foreach(array('edit' => $this->boutonIco("type=edit"),
										'delete' => $this->boutonIco("type=del"), 
										'preview' => $this->boutonIco("type=show"), 
										'sendtest' => $this->boutonIco("type=test"), 
										'send' => $this->boutonIco("type=mail")) 
						as $action => $view) {
				echo "<td rel='$action'>";
				echo $this->tagAnchor($this->url(array('action' => $action,
																							 'id' => $this->newsletter->getId())),
															$view);
				echo '</td>';
		}
	 ?>
</tr>
