<li>
 <span class='titre'>
	 <?php 
		 echo $this->tagAnchor($this->url(array('action' => 'edit',
																						'id' => $this->newsletter->getId())), 
													 htmlentities($this->newsletter->getTitre(), ENT_QUOTES, 'UTF-8'));

    foreach(array('delete' => 'Supprimer', 'send' => 'Envoyer') 
						as $action => $label) {
			echo ' - ';
      echo $this->tagAnchor($this->url(array('action' => $action,
																						 'id' => $this->newsletter->getId())),
														$label);
		}
	 ?>
 </span>
</li>