<script src="<?php echo URL_ADMIN_JS?>common.js"> </script>
<script src="<?php echo URL_ADMIN_JS?>subModal.js"> </script>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_ADMIN_CSS?>subModal.css" />

<?php echo $this->BarreLocalisation($this->id_zone,$this->id_bib); ?>
<div class="form">
	<form name="form" action="<?php echo BASE_URL ?>/admin/rss/rss<?php echo $this->action; ?>" method="post">
		<fieldset>
			<legend><?php echo $this->traduire('RSS'); ?></legend>
			<span id="abonne_erreur" class="abonne"><?php echo $this->message; ?></span>
			<table>
				<tr>
					<td class="droite"><?php echo $this->traduire('Catégorie'); ?></td>
					<td class="gauche" style="width:536px;"><?php echo $this->combo_cat; ?></td>
				</tr>
				<tr>
					<td class="droite"><?php echo $this->traduire('Titre'); ?> *</td>
					<td class="gauche"><input type="text" size="60" id="titre" name="titre" onkeypress="if (event.keyCode == 13) {javascript:PicToolbarOver( getElementById('menu_item975'), 'menu_item975');this.form.submit();return false;}" value="<?php echo $this->escape(trim($this->rss->TITRE));?>" maxlength="80"/></td>
				</tr>
				<tr>
					<td class="droite"><?php echo $this->traduire('Url'); ?> *</td>
					<td class="gauche"><input type="text" id="xml" name="xml" size="60" onkeypress="if (event.keyCode == 13) {javascript:PicToolbarOver( getElementById('menu_item975'), 'menu_item975');this.form.submit();return false;}" value="<?php echo $this->escape(trim($this->rss->URL));?>" maxlength="250"/>
						<input type="hidden" name="id_rss" value="<?php echo $this->rss->ID_RSS; ?>" /></td>
				</tr>
				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Commentaire'); ?> *</td>
					<td class="gauche"><TEXTAREA name="commentaire" rows="4" cols="42"><?php echo $this->escape(trim($this->rss->DESCRIPTION));?></TEXTAREA></td>
        </tr>
				<tr>
					<td style="font-size:8pt;text-align:right;vertical-align:top;">&nbsp;</td>
					<td  align="center" class="info">Entrez la liste des mots-clefs  et expressions qui caractérisent le fil RSS séparés  avec des ;</td>
				</tr>
        <tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Tags'); ?></td>
					<td class="gauche"><TEXTAREA name="tags" rows="4" cols="42"><?php echo $this->escape(trim($this->rss->TAGS));?></TEXTAREA></td>
        </tr>
			</table>
		</fieldset>
		<table>
			<tr>
				<td align="right"> <?php echo $this->bouton('type=V'); ?></td>
				<td>  <?php $url = 'url='.BASE_URL.'/admin/rss?z='.$this->sess_id_zone.'&b='.$this->sess_id_site ;
					echo $this->bouton('id=c_2','picto=del.gif','texte=Annuler',$url,'largeur=120px'); ?>
				</td>
			</tr>
		</table>
		<input type="hidden" name="id_rss" value="<?php echo $this->rss->ID_RSS; ?>"/>
	</form>
</div>
<br>
<br>

<script>
oField = document.getElementById('titre');
oField.focus();
</script>
