<table cellspacing="2" width="100%">
	<tr>
		<td class="droite" width="120px">Effet de transition&nbsp;</td>
		<td class="gauche"><?php
			echo $this->formSelect('op_transition',
														 $this->preferences['op_transition'],
														 '', 
														 ZendAfi_View_Helper_TagSlideshow::getTransitionDefinitions());
		?></td>
	</tr>
	<tr>
		<td class="droite">Hauteur&nbsp;</td>
		<td class="gauche"><?php 
			echo $this->tagSlider('op_hauteur_boite',
														$this->preferences['op_hauteur_boite'], 
														20, 1000, 5); ?></td>
	</tr>
	<tr>
		<td class="droite">Largeur&nbsp;</td>
		<td class="gauche"><?php
		 echo $this->tagSlider('op_largeur_img', 
													 $this->preferences['op_largeur_img'],
													 20, 1000, 5); ?></td>
	</tr>
	<tr>
		<td class="droite">Délai entre chaque image<br />
		<span style="font-size:80%;">(secondes)</span></td>
		<td class="gauche"><?php
		 echo $this->tagSlider('op_timeout', 
													 $this->preferences['op_timeout'],
													 3, 30, 1); ?> (secondes)</td>
	</tr>
</table>