<?php
	 echo $this->partial('flash/_auto_resize.phtml');
?>
<script type="text/javascript" src="<?php echo URL_JS ?>swfobject.js"></script>
	<script type="text/javascript">
	var flashvars = {};
	flashvars.settingsXML = "<?php echo $this->fic_settings ?>";
	flashvars.folderPath = "<?php echo BASE_URL ?>/temp/flash/";
	var params = {};
	params.scale = "noscale";
	params.salign = "tl";
	params.wmode = "transparent";
	var attributes = {};
	swfobject.embedSWF("<?php echo $this->url_flash ?>carrousel_horizontal/carousel.swf", "carouselDiv", "<?php echo $this->largeur_flash; ?>", "300", "9.0.0", false, flashvars, params, attributes);
</script>

<div id="carouselDiv">
