<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
	<responseDate><?php echo date('c');?></responseDate>
	<?php echo $this->request->renderOn($this->builder); ?>
	<?php echo ($this->error) ? $this->error : '';?>
	<Identify>
		<repositoryName><![CDATA[<?php echo $this->repositoryName;?>]]></repositoryName>
		<baseURL><?php echo $this->baseUrl; ?></baseURL>
		<protocolVersion>2.0</protocolVersion>
    <adminEmail><![CDATA[<?php echo $this->adminEmail;?>]]></adminEmail>
		<earliestDatestamp><?php echo $this->earliestDatestamp; ?></earliestDatestamp>
    <deletedRecord>no</deletedRecord>
    <granularity>YYYY-MM-DD</granularity>
	</Identify>
</OAI-PMH>