<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
	<responseDate><?php echo date('c');?></responseDate>
	<?php echo $this->request->renderOn($this->builder); ?>
	<?php echo ($this->error) ? $this->error : '';?>
	<?php if ($this->headers) { ?>
	<ListIdentifiers>
		<?php echo $this->headers; ?>
	</ListIdentifiers>
	<?php } ?>
	<?php echo ($this->token) ? $this->token->renderOn($this->builder): '' ?>
</OAI-PMH>
