<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
	<responseDate><?php echo date('c');?></responseDate>
	<?php echo $this->request->renderOn($this->builder); ?>
	<?php if ($this->sets) { ?>
	<ListSets>
		<?php echo $this->sets;?>
	</ListSets>
	<?php } ?>
</OAI-PMH>