<?php echo $this->BarreLocalisation($this->id_zone,$this->id_bib); ?>

<div class="form">
	<form name="form" action="<?php echo BASE_URL ?>/admin/sito/sito<?php echo $this->action; ?>" method="post">
		<fieldset>
			<legend><?php echo $this->traduire('Sitothèque'); ?></legend>
			<span id="abonne_erreur" class="abonne"><?php echo $this->message; ?></span>
			<table>
				<tr>
					<td class="droite"><?php echo $this->traduire('Catégorie'); ?> </td>
					<td class="gauche" style="width:536px;"><?php echo $this->combo_cat; ?> </td>
				</tr>
				<tr>
					<td class="droite"> <?php echo $this->traduire('Titre'); ?> *</td>
					<td class="gauche"> <input type="text" id="titre"  size="60" name="titre" onkeypress="if (event.keyCode == 13) {javascript:PicToolbarOver( getElementById('menu_item975'), 'menu_item975');this.form.submit();return false;}" value="<?php echo $this->escape(trim($this->sito->TITRE));?>" maxlength="80"/></td>
				</tr>
				<tr>
					<td class="droite"> <?php echo $this->traduire('Url'); ?> *</td>
					<td class="gauche"> <input type="text" name="url" size="60" onkeypress="if (event.keyCode == 13) {javascript:PicToolbarOver( getElementById('menu_item975'), 'menu_item975');this.form.submit();return false;}" value="<?php echo $this->escape(trim($this->sito->URL));?>" maxlength="250"/></td>
				</tr>
				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Commentaire'); ?></td>
					<td class="gauche"> <TEXTAREA name="commentaire" rows="5" cols="50"><?php echo $this->escape(trim($this->sito->DESCRIPTION));?></TEXTAREA></td>
				</tr>
				<tr>
					<td style="font-size:8pt;text-align:right;vertical-align:top;">&nbsp;</td>
					<td  align="center" class="info">Entrez la liste des mots-clefs  et expressions qui caractérisent ce site séparés  avec des ;</td>
				</tr>
				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Tags'); ?></td>
					<td class="gauche"> <TEXTAREA name="tags" rows="5" cols="50"><?php echo $this->escape(trim($this->sito->TAGS));?></TEXTAREA>
						<input type="hidden" name="id_sito" value="<?php echo $this->sito->ID_SITO; ?>" /></td>
				</tr>

			</table>
		</fieldset>
		<table>
			<tr>
				<td align="right"> <?php echo $this->bouton('type=V'); ?></td>
				<td>  <?php $url = 'url='.BASE_URL.'/admin/sito?z='.$this->sess_id_zone.'&b='.$this->sess_id_site ;
							echo $this->bouton('id=c_2','picto=del.gif','texte=Annuler',$url,'largeur=120px'); ?>
				</td>
			</tr>
		</table>
	</form>
</div>
<br>


<script>
oField = document.getElementById('titre');
oField.focus();
</script>
