<script src="<?php echo JQUERY; ?>" type="text/javascript"> </script>
<script src="<?php echo URL_ADMIN_JS; ?>multi_upload/fileuploader.js" type="text/javascript"> </script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_CSS?>global.css">
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_ADMIN_JS?>multi_upload/fileuploader.css">
<script>
	function createUploader()
	{
		var uploader = new qq.FileUploader({
		element: document.getElementById('file_uploader'),
		action: '<?php echo BASE_URL ?>/opac/upload/fichiermultiple?type=<?php echo $this->type?>&id_dossier=<?php echo $this->id_dossier?>',
		debug: true
		});
	}
</script>
<div id="file_uploader"></div>
<script>$(document).ready(createUploader)</script>
