<style type='text/css'>
	 #entrepot_id {
			width: 400px;
	 }

	 #oai_set {
			width: 400px;
	 }

	 #import_progress div{
		 float:left;
	 }

	 #progress_bar {
		 width:200px;
		 text-align: right;
	 }

	 #error {
		 color: red;
		 font-weight: bold;
		 width: 600px;
		 font-size: 0.8 em;
		 padding: 10px;
	 }

	 input[type=submit] {
		 width:150px;
	 }
</style>


<?php 

echo '<h2>'.$this->titre.'</h2>';

if ($this->entrepot_id) { 
	if (count($this->oai_sets) == 0)	{?>
			 <div id='error'>
					Aucun catalogue retourné pour <?php echo $this->entrepots[$this->entrepot_id] ?>
			 </div>
<?php } else { ?>

	 
	<form id='oai_harvest_set'>
		 <?php echo $this->formHidden('entrepot_id', $this->entrepot_id); ?>
		 <div>Catalogue:</div>
		 <?php echo $this->formSelect("oai_set", $this->oai_set, "", $this->oai_sets) ?>
		 <input	 type='submit' value='Importer'>
	</form>


	<div id='import_progress' style='display:none'>
		 <div>Import des notices:</div>
		 <div id='progress_bar'>&nbsp;</div>
		 <div class="icon_loading">
			 <img src="<?php echo URL_ADMIN_IMG.'loading.gif' ?>" /> 
		 </div>
	</div>


	<script type='text/javascript'>
		 var oai_harvest = function(entrepot_id, oai_set, token) {
			 var harvest_url = '<?php echo BASE_URL.'/admin/oai/harvest' ?>';
			 var params = {'entrepot_id': entrepot_id,
										 'oai_set': oai_set,
										 'resumption_token': token};
			 $.getJSON(harvest_url, params, function(data) {
					 if (data == null) {	 
						 $('#progress_bar').text('Aucune donnée retournée');
						 $('#import_progress .icon_loading').hide();
						 return;
					 }

					 if (data['token']==null) {
						 $('#progress_bar').text('Catalogue importé');
						 $('#import_progress .icon_loading').hide();
						 return;
					 }

					 $('#progress_bar').text(data['cursor']+'/'+data['list_size']);
					 oai_harvest(entrepot_id, oai_set, data['token']);
			 });
		 }


		 $(document).ready(function(){
				 $('#oai_harvest_set').submit(function() {
						 $('#import_progress').children().andSelf().show();
						 oai_harvest(<?php echo $this->entrepot_id ?>, $('#oai_set').val(), '');
						 return false;
					 });
			 });
	</script>
<?php }} ?>
