<?php
echo $this->bouton('id=add_category',
									 'picto=add.gif',
									 'texte=' . $this->traduire('Ajouter un entrepôt'),
									 'url=' . $this->url(array('action' => 'add',
																						 'id' => null))
									 );
?>

<table id="entrepots_oai" class="models">
	<thead>
		<tr>
			<th>Libellé</th>
			<th>URL</th>
			<th class="actions" style="width:50px;">Action</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->entrepots as $entrepot) { ?>
		<tr>
			<td><?php echo $this->escape($entrepot->getLibelle());?></td>
			<td><?php echo $this->escape($entrepot->getHandler());?></td>
			<td><?php 
				echo $this->tagAnchor($this->url(array('action' => 'edit',
																							 'id' => $entrepot->getId())),
															$this->boutonIco('type=edit'));
				echo $this->tagAnchor($this->url(array('action' => 'browse',
																							 'id' => $entrepot->getId())),
															$this->boutonIco('type=show'));
				echo $this->tagAnchor($this->url(array('action' => 'delete',
																							 'id' => $entrepot->getId())),
															$this->boutonIco('type=del'));
				?>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>




<?php 
	echo $this->subview;

	echo $this->renderForm($this->search_form);

	if ($this->notices) {
		echo '<ul>';
		foreach ($this->notices as $notice)
			echo sprintf('<li>%s - %s</li>',
									 $notice->getTitre(),
									 $this->tagAnchor(array('action' => 'import',
																					'id' => $notice->getId()), 
																		'Importer'));
		echo '</ul>';
	}


?>