<?php
echo $this->bouton('id=add_category',
									 'picto=add.gif',
									 'texte=' . $this->traduire('Ajouter un entrepôt'),
									 'url=' . $this->url(array('action' => 'add',
																						 'id' => null))
									 );

echo $this->tagModelTable($this->entrepots, 
													array($this->_('Libellé'), 'URL'),
													array('libelle', 'handler'),
													array(array('action' => 'edit', 'content' => $this->boutonIco('type=edit')),
																array('action' => 'browse', 'content' => $this->boutonIco('type=show')),
																array('action' => 'delete', 'content' => $this->boutonIco('type=del'))),
													'entrepots_oai');

echo $this->subview;

echo $this->renderForm($this->search_form);

if ($this->error) echo '<div class="error">'.$this->error.'</div>';

if ($this->notices) {
	echo '<ul>';
	foreach ($this->notices as $notice)
		echo sprintf('<li>%s - %s</li>',
								 $notice->getTitre(),
								 $this->tagAnchor(array('action' => 'import',
																				'id' => $notice->getId()), 
																	'Importer'));
	echo '</ul>';
}


?>