<!DOCTYPE html >
<html lang="<?php echo $this->_translate()->getLocale() ?>">
<head>
	<title><?php echo $this->titre ?></title>
<?php $current_profil = Class_Profil::getCurrentProfil(); ?>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="description" content="<?php echo $current_profil->getCommentaire();?>" />
<meta name="keywords" content="<?php echo $current_profil->getRefTags();?>" />
<meta content="all" name="robots" />
<meta content="10 days" name="revisit-after" />
<?php 
	echo $current_profil->getStyleCss();
  if ($current_profil->hasFavicon())
		echo sprintf('<link rel="shortcut icon" href="%s"/>', $current_profil->getFavicon());

$head_scripts = Class_ScriptLoader::newInstance()
	->addStyleSheet(URL_ADMIN_JS.'jquery_ui/css/jquery.ui.afi.theme')
	->addOPACStyleSheet('global', 'nuages')
	->addSkinStyleSheets(array('global', 'erreur', 'dialog', 'popup'))
	->addAdminStyleSheet('subModal')
	->addOPACStyleSheet('print', array('media' => 'print'))
	->addInlineScript(sprintf('var baseUrl="%s"; var imagesUrl="%s"; var cssUrl="%s"; var userFilesUrl="%s"',
														BASE_URL, URL_IMG, URL_CSS, USERFILESURL))
	->loadJQuery()
	->loadJQueryUI()
	->addAdminScripts(array('onload_utils', 'global', 'toolbar', 'common', 'subModal'))			 
	->addOPACScripts(array('abonne', 'menu', 'bib', 'avis', 'recherche', 'jquery.placeholder.min'))
	->addJQueryReady('$("input").placeholder()')
	->addJQueryReady('setupAnchorsTarget()')
	->showNotifications();


if (($user = Class_Users::getLoader()->getIdentity())
		&& $user->isAdmin())
	$head_scripts->addJQueryReady('
    var currentPositions = [0, 0, 0];
    $("div.layout-division>div>div").each(function(k, item) {
      var division = $(item).parents("div.layout-division").attr("id").split("-").pop();
      $(item).attr("data-position", currentPositions[division-1]);
      currentPositions[division-1]++;
      $(item).attr("data-division", division);
    });

    $("div.layout-division>div").sortable({
      cursor:"move",
      connectWith:"div.layout-division>div",
      stop: function(event, ui){
        var newDivision = $(ui.item).parents("div.layout-division").attr("id").split("-").pop();
        var newPosition = $(ui.item).prevAll().length;
        if (newDivision == $(ui.item).attr("data-division")
            && newPosition == $(ui.item).attr("data-position")) 
          return;

        $.ajax("' . $this->url(array('module' => 'admin',
																					'controller' => 'profil',
																					'action' => 'module-sort'), null, true) . '",
               {data: {fromDivision: $(ui.item).attr("data-division"),
                      toDivision: newDivision,
                      fromPosition: $(ui.item).attr("data-position"),
                      toPosition: newPosition,
                      profil:' . $current_profil->getId() . '}});
      }});
  ');

if (file_exists(PATH_SKIN.'/css/bib.css'))
	$head_scripts->addSkinStyleSheet('bib');

if ($this->header_css)
	$head_scripts->addStyleSheet($this->header_css);

if ($this->accessibilite_on) {  //Feuilles de styles pour les déficiences visuelles
	$head_scripts
		->addOPACStyleSheet('blanc_sur_noir', array('rel' => 'alternate stylesheet',
																								'title' => $this->_('Blanc sur noir')))
		->addOPACStyleSheet('noir_sur_blanc', array('rel' => 'alternate stylesheet',
																								'title' => $this->_('Noir sur blanc'))) 
		->addOPACStyleSheet('bleu_sur_jaune', array('rel' => 'alternate stylesheet',
																								'title' => $this->_('Bleu sur jaune')))
		->cssAddLine($this->_('<link rel="alternate stylesheet" type="text/css" href="" title="%s" />', 
													'Style par défaut'))
		->cssAddLine('<link id="accessibility_stylesheet" rel="stylesheet" type="text/css" href="" title="" />')
		->addAdminScript('jquery.cookie')
		->addJQueryReady('initAccessibilityOptions();');
}

if (Class_AdminVar::get('ID_READ_SPEAKER'))
	$head_scripts
		->addJQueryReady(sprintf('$.getScript("http://wr.readspeaker.com/webreader/webreader.js.php?cid=%s")',
														 getVar('ID_READ_SPEAKER')));

$script_loader = Class_ScriptLoader::getInstance();
$head_scripts->renderStyleSheets();
$script_loader->renderStyleSheets();



foreach(array(7,8) as $ie) {
	if (file_exists(PATH_SKIN.'/css/ie'.$ie.'.css')) {
		echo sprintf('<!--[if IE %d]><link rel="stylesheet" type="text/css" href="%sie%d.css" /><![endif]-->',
								 $ie, URL_CSS, $ie);
	}

	$ie_css = $current_profil->getHeaderCssIE($ie);
	if (file_exists(USERFILESPATH.'/css/'.$ie_css ))
		echo sprintf('<!--[if IE %d]><link rel="stylesheet" type="text/css" href="%s/css/%s" /><![endif]-->',
								 $ie, USERFILESURL, $ie_css);
}


$head_scripts->renderJavaScripts();
$script_loader->renderJavaScripts();
?>
</head>
