<?php 
$script_loader = Class_ScriptLoader::getInstance()
	->addAdminScript('onload_utils')
	->addInlineScript(sprintf('var imagesUrl = "%s";', URL_IMG));

if (file_exists(PATH_SKIN.'/css/iframe.css'))
	$script_loader->addSkinStyleSheet('iframe');

ob_start(); 
echo $this->render($this->actionScript);
$html_contents = ob_get_contents();
ob_end_clean();
?>

<!DOCTYPE html>
<html lang="<?php echo $this->_translate()->getLocale() ?>">
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
	<?php echo $script_loader->html();	?>
</head>

<body style="margin:0px;padding:0px;background-color:transparent;background-image:none" class="auto_resize iframe">
	<?php echo $html_contents; ?>
</body>

</html>
