<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="<?php echo $this->_translate()->getLocale() ?>" xml:lang="<?php echo $this->_translate()->getLocale() ?>" xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
</head>

<body>
 <!-- RSPEAK_START -->
  <?php echo $this->render($this->actionScript); ?>
 <!-- RSPEAK_STOP -->
</body>
</html>
