<?php 
$script_loader = Class_ScriptLoader::getInstance()
								 ->addAdminStyleSheet('subModalContenu')
								 ->addAdminScript('global');

ob_start(); 
echo $this->render($this->actionScript);
$html_contents = ob_get_contents();
ob_end_clean();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="<?php echo $this->_translate()->getLocale() ?>" xml:lang="<?php echo $this->_translate()->getLocale() ?>" xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
		<?php echo $script_loader->html();?>
	</head>
	<body><?php echo $html_contents ?></body>
</html>
