<?php $this->openBoite("Catalogue");?>
<br><br>
<div>
	<?php if($this->url_retour_notice)print('<span style="padding-right:10px"><a href="'.$this->url_retour_notice.'">&raquo; Retour à la notice</a></span>'); ?> 
	
	
	Dans INDEX
	
	
</div>
<?php
$this->closeBoite();

// Liste notices
//echo $this->listeNotices($this->liste,$nombre,$page_cours,$preferences);
//echo '<br><div style="width:100%;text-align:center;">'.$this->pager($nombre,$preferences["liste_nb_par_page"],$page_cours,$url_retour).'</div>';
?>