<?php
echo $this->bouton('id=add_category',
									 'picto=add.gif',
									 'texte=' . $this->traduire('Ajouter une collection'),
									 'url=' . $this->url(array('action' => 'add_categorie',
																					 'id' => null))
);


echo $this->form_import_ead;
?>

<?php 
echo $this->getHelper('TreeView')->renderItemWithIconeSupport()->treeView($this->categories, 
																																				 $this->containersActions, 
																																				 $this->itemsActions, 
																																				 false); 
?>
