<?php
echo $this->profileSelect('bib',$this->id_zone,$this->id_bib,'z'); 
echo ('<center><div align="center"><br>'.$this->bouton('id=c_19','picto=add.gif','texte='.$this->traduire('Ajouter une bibliothèque').'','url='.BASE_URL.'/admin/bib/add','largeur=220px').'</div></center>');  
?>
<br /><table cellspacing="0" cellpadding="0">
    <tr class="soustitre">    
        <td>Ville</td>
        <td>Libelle</td>
        <td colspan="6"> Action</td>
    </tr>
     <tr>
      	<td colspan="8"  class="separ"> </td>
      </tr>
    
<?php 
$ligne = 0;
foreach ($this->bib_array as $bib) {
	$ico_del = $bib->isBibDeletable()
		? '<a href="'.BASE_URL.'/admin/bib/delete/id/'.$bib->getId().'">'.$this->boutonIco("type=del").'</a>'
	  : '<a href="#" onclick="alert(\'Cette bibliothèque possède encore du contenu\'); return false;"><img src="'.URL_ADMIN_IMG.'ico/del.gif" class="ico" alt="Supprimer" title="Supprimer"/></a>';
    
    
    $ligne ++ ; if ($ligne & 1) $class="first"; else $class="second";
    $ville = ucfirst($bib->getVille());
    echo '<tr class="'.$class.'">'.
				 '<td valign="top">'.$ville. '</td>'.
				 '<td valign="top" align="left">'.$bib->getLibelle().'</td>'.
				 '<td valign="top" align="center"><a href="'.BASE_URL.'/admin/bib/edit/id/'.$bib->getId().'">'.$this->boutonIco("type=edit").'</a></td>'.
				 '<td valign="top" align="center">'.$ico_del.'</td>';



		$action = '<td valign="top" align="center"><a href="%s"><img src="'.URL_ADMIN_IMG.'picto/%s" border="0" alt="%3$s" title="%3$s"/></a></td>';
		echo sprintf($action, 
								 $this->url(array('action' => 'planacces',
																	'id_bib' => $bib->getId())),
								 'map.gif',
								 $this->_('Configurer le plan d\'accès'));

		echo sprintf($action, 
								 $this->url(array('action' => 'plans',
																	'id_bib' => $bib->getId())),
								 'plan.gif',
								 $this->_('Plans de la bibliothèque'));

		echo sprintf($action, 
								 $this->url(array('action' => 'localisations',
																	'id_bib' => $bib->getId())),
								 'localisation.gif',
								 $this->_('Localisations de la bibliothèque'));

		if (Class_AdminVar::isPlanningOuverturesEnabled())
				echo sprintf($action, 
										 $this->url(array('controller' => 'ouvertures',
																			'action' => 'index',
																			'id_site' => $bib->getId())),
										 'calendar.gif',
										 $this->_('Planification des ouvertures'));
																		 
    echo '</tr>';
}

echo ('</table>');
echo '<span id="abonne_erreur" class="abonne">'.$this->errorMessage.'</span>'; ?>


<div id="ajax"></div>
