<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_ADMIN_JS ?>slimbox/slimbox2.css">
<script src="<?php echo URL_ADMIN_JS ?>tag_selection.js" type="text/javascript"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>slimbox/slimbox2.js"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>jquery_ui/jquery.ui.core.min.js"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>jquery_ui/jquery.ui.widget.min.js"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>jquery_ui/jquery.ui.mouse.min.js"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>jquery_ui/jquery.ui.draggable.min.js"> </script>

<script>
	// Rendre le point draggable et effacer le x,y si on change de plan
	$(function()
	{
		$('#point_localisation').draggable
		({
			containment: '#lbImage',
			drag: function(event, ui)
			{
				container=$('#lbImage').offset();
				$('#POS_Y').attr('value',ui.position.top-container.top);
				$('#POS_X').attr('value',ui.position.left-container.left);
			}
		})
		$('#ID_PLAN').change(function()
		{
			$('#POS_X').attr('value','0');
			$('#POS_Y').attr('value','0');
		});
	});


	// Init function de fin du load ajax
	jQuery(function($) 
	{
		$('#plan').ajaxStop(function()
		{
			$('#patience').css('display','none');
			if($(this).html()=="ERREUR") {alert("Impossible de trouver l'image de ce plan."); return;}
			$('#ref_plan').attr('title',$('#LIBELLE').val());
			jQuery(function($) {
				$("a[rel^='lightbox']").slimbox({onClose:function(){$('#point_localisation').css('display','none')}},null,null);
			});
			$('#point_localisation > img').attr('src',$('#select_ANIMATION').attr('src'));
			$('#img_plan').trigger('click');
			imageLoaded();
		});
	});
	
	// Verif si le slimbox est affiché
	function imageLoaded()
	{
		if($('#lbBottomContainer').css('display')=='none')
		{
			window.setTimeout(imageLoaded,1000);
			return;
		}
		container=$('#lbImage').offset();
		x=container.left+parseInt($('#POS_X').val());
		y=container.top+parseInt($('#POS_Y').val());
		$('#point_localisation')
			.css('display','block')
			.css('top',y+'px')
			.css('left',x+'px');
	}

	// Affichage du plan
	function afficherPlan()
	{
		var id_plan=$("#ID_PLAN").val();
		if(id_plan=="0") {alert("Sélectionnez le plan a associer à cette localisation."); return; }
		$('#patience').css('display','block');
		$('#plan').load('<?php echo BASE_URL ?>/admin/bib/ajaximageplan/id_plan/'+id_plan);
	}
</script>

<div id="plan" style="display:none"></div>
<div id="point_localisation" style="position:absolute;z-index:10000;display:none;cursor:pointer"><img src="<?php echo URL_ADMIN_IMG ?>point_localisation.gif" border="0"></div>

<h3>Bibliothèque : <?php echo $this->nom_bib ?></h3>

<center>
<div class="form" align="center" >
	<form name="form" action="<?php print(BASE_URL.'/admin/bib/localisationsmaj/id_localisation/'.$this->id_localisation.'?id_bib='.$this->id_bib) ?>" method="post">

		<fieldset>
			<legend><?php echo $this->traduire('Localisation'); ?> </legend>
			<?php
			if($this->erreurs)
			{
				echo '<p class="error">';
				foreach($this->erreurs as $erreur) print($erreur.BR);
				echo '</p>';
			}
			?>
			<table border="0" cellpadding="5" cellspacing="0">
				<tr>
					<td class="droite" style="width:150px;">Libellé</td>
					<td class="gauche"><input type="text" id="LIBELLE" name="LIBELLE"style="width:100%" value="<?php echo $this->escape(trim($this->localisation["LIBELLE"]));?>" maxlength="100"/></td>
				</tr>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Description'); ?></td>
					<td class="gauche"><TEXTAREA name="DESCRIPTION" rows="4" cols="42"><?php echo $this->escape(trim($this->localisation["DESCRIPTION"]));?></TEXTAREA></td>
				</tr>

				<tr>
					<td class="droite"><?php echo $this->traduire('Plan associé'); ?></td>
					<td class="gauche">
						<input type="hidden" name="POS_X" id="POS_X" value="<?php echo $this->localisation["POS_X"] ?>">
						<input type="hidden" name="POS_Y" id="POS_Y" value="<?php echo $this->localisation["POS_Y"] ?>">
						<?php echo $this->formSelect("ID_PLAN", $this->localisation["ID_PLAN"],"",$this->plans) ?>&nbsp;&nbsp;
						<a href="#" onclick="afficherPlan()">&raquo;&nbsp;Placer sur le plan</a>
					</td>
				</tr>

				<tr>
					<td colspan="2">
						<div id="patience" style="width:100%;display:none" align="center"><img src="<?php echo URL_ADMIN_IMG ?>loading.gif"></div>
					</td>
				</tr>

				<tr>
					<td class="droite"><?php echo $this->traduire('Animation'); ?></td>
					<td class="gauche">
						<?php echo $this->ChoixPictogramme("plan_animation","ANIMATION",0,$this->localisation["ANIMATION"]); ?>
					</td>
				</tr>

			</table>
		</fieldset>

		<fieldset>
			<legend><?php echo $this->traduire('Critères de reconnaissance'); ?></legend>
			<table>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Types de documents'); ?></td>
					<td class="gauche"><?php echo $this->TagListeCoches("type_doc","TYPE_DOC",$this->localisation["TYPE_DOC"]); ?></td>
				</tr>
				
				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Annexe'); ?></td>
					<td class="gauche"><?php echo $this->TagListeCoches("annexe","ANNEXE",$this->localisation["ANNEXE"],$this->id_bib); ?></td>
				</tr>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Sections'); ?></td>
					<td class="gauche"><?php echo $this->TagListeCoches("section","SECTION",$this->localisation["SECTION"]); ?></td>
				</tr>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Emplacements'); ?></td>
					<td class="gauche"><?php echo $this->TagListeCoches("emplacement","EMPLACEMENT",$this->localisation["EMPLACEMENT"]); ?></td>
				</tr>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('Cotes - depuis'); ?></td>
					<td class="gauche"><input type="text" name="COTE_DEBUT" size="10" value="<?php echo $this->localisation["COTE_DEBUT"];?>" maxlength="10"/></td>
				</tr>

				<tr>
					<td class="droite" valign="top"><?php echo $this->traduire('jusqu\'à'); ?></td>
					<td class="gauche"><input type="text" name="COTE_FIN" size="10" value="<?php echo $this->localisation["COTE_FIN"];?>" maxlength="10"/></td>
				</tr>

			</table>
		</fieldset>

		<fieldset>
			<legend><?php echo $this->traduire('Photo'); ?></legend>
			<table>
				<tr>
					<td class="droite"><?php echo $this->tagUpload("IMAGE","localisation_bib",$this->localisation["IMAGE"]) ?></td>
				</tr>
			</table>
		</fieldset>

		<table>
			<tr>
				<td align="right" style="padding-right:5px;"><?php echo $this->bouton('type=V'); ?> </td>
				<td align="left" style="padding-left:5px;"> <?php echo $this->bouton('id=29','picto=del.gif','texte=Annuler','url='.BASE_URL.'/admin/bib/localisations?id_bib='.$this->id_bib,'largeur=120px'); ?></td>
			</tr>
		</table>
	</form>
</div>
</center>