<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_ADMIN_JS ?>slimbox/slimbox2.css">
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>slimbox/slimbox2.js"> </script>
<script type="text/javascript" src="<?php echo URL_ADMIN_JS?>slimbox/autoload_image_simple.js"> </script>

<?php
echo ('<center><div align="center"><br>'.$this->bouton('id=c_19','picto=add.gif','texte='.$this->traduire('Ajouter un plan').'','url='.BASE_URL.'/admin/bib/plansmaj?id_bib='.$this->id_bib.'&creation=1','largeur=170px').'</div></center>');  ?>
<br />

<?php
if($this->plans)
{
	?>
<table cellspacing="0" cellpadding="0">
	<tr class="soustitre">
		<td style="width:30%">Libellé</td>
		<td style="width:60%;">Description</td>
		<td style="width:10%;">Image</td>
		<td style="width:30px;padding-left:10px;" colspan="4">Action</td>
	</tr>
	<tr>
		<td colspan="6"  class="separ"> </td>
	</tr>
	<?php
	foreach ($this->plans as $plan)
	{
		$image=BASE_URL.'/userfiles/photobib/plans/'.$plan["IMAGE"];
		$test=fetchOne("select count(*) from bib_localisations where ID_PLAN=".$plan["ID_PLAN"]);
		if($test == 0) $ico_del = '<a href="'.BASE_URL.'/admin/bib/plansdelete/id_plan/'.$plan["ID_PLAN"].'?id_bib='.$this->id_bib.'">'.$this->boutonIco("type=del").'</a>';
		else $ico_del ='<a href="#" onclick="alert(\'Ce plan a encore des localisations associées. \'); return false;"><img src="'.URL_ADMIN_IMG.'ico/del.gif" class="ico" alt="Supprimer" title="Supprimer"/></a>';
		$ligne ++ ; if ($ligne & 1) $class="first"; else $class="second";
		echo('<tr class="'.$class.'">
			<td>'.$plan["LIBELLE"]. '</td>
			<td>'.$plan["DESCRIPTION"].'</td>
			<td>
				<a href="'.$image.'" rel="lightbox" title="'.$plan["LIBELLE"].'">
				<img src="'.$image.'" width="100" border="0">
				</a>
			</td>
			<td align="center"><a href="'.BASE_URL.'/admin/bib/plansmaj/id_plan/'.$plan["ID_PLAN"].'?id_bib='.$this->id_bib.'?id_bib='.$this->id_bib.'">'.$this->boutonIco("type=edit").'</a></td>
			<td align="center">'.$ico_del.'</td>
		</tr>');
	}
	?>
	</tr>
  <tr><td colspan="20" style="background:transparent url(<?php echo URL_IMG; ?>box/menu/separ.gif) repeat-x scroll center bottom">&nbsp;</td></tr>
	<tr><td colspan="20" style="text-align:left"><a href="<?php echo BASE_URL.'/admin/bib' ?>">Retour</a></td></tr>
	<?php
	echo ('</table>');
}
else echo '<p class="error" align="center">Il n\'y a aucun plan associé à cette bibliothèque.</p>';
?>

