<?php
$preferences = $this->current_module["preferences"];

$hasFacettes	= (1 == $preferences["facettes_actif"]);
$hasTags			= (1 == $preferences["tags_actif"]);
$tagsPosition	= $preferences["tags_position"];

$titre=$this->_("Résultat de la recherche");

if ($this->is_pertinence) {
	$titre .= $this->_(" (recherche élargie triée par pertinence)");
}

$this->openBoite($titre);

print($this->texte_selection);
?>

<div class="recherche_actions">
	<span>
	<?php 
	echo $this->tagAnchor($this->url_retour_recherche_initiale, 
												sprintf('&raquo; %s', 
																$this->_('Retour à la recherche initiale')));?>
  </span> 
	<?php if ($this->url_retour_notice) { ?>
		<span>
		<?php 
		echo $this->tagAnchor($this->url_retour_notice, 
													sprintf('&raquo; %s', 
																	$this->_('Retour à la notice'))); ?>
		</span>
	<?php } ?>

	<span>
  <?php echo $this->tagAnchor($this->url_nouvelle_recherche, 
															'&raquo; '.$this->_('Nouvelle recherche')); ?>
  </span>

  
	<span>
	<?php if ((int)$preferences['suggestion_achat'] == 1)
           echo $this->tagAnchor(['controller' => 'abonne', 'action' => 'suggestion-achat'], 
																 '&raquo; '.$this->_('Suggérer un achat'));?>
  </span> 
</div>


<?php
$this->closeBoite();

extract($this->resultat);
if (!isset($tags)) $tags=[];
?>

<div style="width:100%" class="conteneur_simple">
	<?php
	// Si facettes ou tags on ouvre un tableau a 2 colonnes
	if ($hasFacettes	or ($hasTags and (2 == $tagsPosition))) 
	{
		?>
		<table class="resultat_recherche" style="width:100%">
			<tr>
				<td style="vertical-align:top" style="width: 65%">
		<?php
	}

	// Liste notices
	echo $this->listeNotices($this->liste, 
													 $nombre, 
													 $page_cours, 
													 $preferences, 
													 $this->url_retour, 
													 $this->tri);
	?>
	<br/>
	<div style="width:100%;text-align:center;">
	<?php 
	echo $this->pager($nombre, 
										$preferences["liste_nb_par_page"], 
										$page_cours, 
										$this->url_retour);?>
  </div>
	<?php
	// Container notice pour listes d'images
	if (3 < $preferences["liste_format"]) {
		$notice_html= new Class_NoticeHtml();
		print($notice_html->getConteneurNotice("notice"));
	}

	// Tags sous la liste
	if ($hasTags and (1 == $tagsPosition)) {
		print(BR . $this->nuageTags($tags, $preferences["tags_codes"], $this->url_retour));
	}

	// Facettes et tags sous les facettes
	if ($hasFacettes or $hasTags) { ?>
		</td>
		<td style="vertical-align:top;width: 35%">
		<?php
		if ($nombre) {
			if ($hasFacettes) { ?>
				<div class="facette_outer" style="margin-left:10px;margin-top:17px">
					<?php if ($preferences["facettes_message"]) { ?>
						<strong><?php echo $preferences["facettes_message"];?></strong><br/>
					<?php } ?>
					<?php echo $this->facettes($facettes, $preferences, $this->url_facette); ?>
				</div>
			<?php
			}

			if ($hasTags and (2 == $tagsPosition)) { ?>
				<div class="nuage_outer" style="margin-left:10px"><br/>
					<?php if ($preferences["tags_message"]) { ?>
						<strong><?php echo $preferences["tags_message"];?></strong>
					<?php } ?>
					<?php echo $this->nuageTags($tags, $preferences["tags_calcul"], $this->url_retour); ?>
				</div>
			<?php
			}
		}
		?>
		</td>
		</tr>
	</table>
	<?php } ?>

</div>

<script src="<?php echo URL_JS?>recherche.js" type="text/javascript"> </script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo URL_CSS?>recherche.css" />