<?php

if($user = Class_Users::getLoader()->getIdentity()) {
	echo sprintf("<div>%s %s </div>", $this->_("Bienvenue"), $user->getNomAff());	
} else {
	echo $this->newForm(array('autocomplete' => 'off'))
		->setAction($this->url(array('controller' => 'auth', 
																 'action' => 'boitelogin', 
																 'id_module' => $this->id_module)))
		->addElement('text', 'username', array('label' => $this->preferences['identifiant'],
																					 'placeholder' => $this->preferences['identifiant_exemple'],
																					 'size' => 15))
		->addElement('password', 'password', array('label' => $this->preferences['mot_de_passe'],
																							 'placeholder' => $this->preferences['mot_de_passe_exemple'],
																							 'size' => 15))
		->setElementDecorators(array('ViewHelper', 'Label'))
		->addElement('submit', 'login', array('label' => $this->preferences['lien_connexion'],
																					'decorators' => array('ViewHelper')));
}
?>