<center>
<div class="form" align="center" >
	<form name="form" method="post">

		<fieldset>
			<legend><?php echo $this->traduire('Catalogue'); ?> </legend>
			<?php
      if($this->catalogue->hasErrors())	{
				echo '<p class="error">';
				echo implode(BR, $this->catalogue->getErrors());
				echo '</p>';
			}
			?>
				<table border="0" cellpadding="5" cellspacing="0">
					<tr>
						<td class="droite" style="width:150px;"><?php echo $this->traduire('Libelle'); ?></td>
						<td class="gauche"><input type="text" name="libelle" value="<?php echo $this->catalogue->getLibelle()?>" maxlength="50" size="50" onchange="setFlagMaj(true)"></td>
					</tr>

					<tr>
						<td class="droite" style="width:150px;"><?php echo $this->traduire('Description'); ?></td>
						<td class="gauche"><textarea name="description" rows='10' onchange="setFlagMaj(true)"><?php echo $this->catalogue->getDescription()?></textarea></td>
					</tr>

				</table>
		</fieldset>

	  <?php if (Class_AdminVar::isOAIServerEnabled()) { ?>
    <fieldset>
			<legend><?php echo $this->traduire('Serveur OAI'); ?> </legend>
		  <table border="0" cellpadding="5" cellspacing="0">
					<tr>
						<td class="droite" style="width:150px;"><?php echo $this->traduire('OAI spec'); ?></td>
						<td class="gauche"><input type="text" name="oai_spec" value="<?php echo $this->catalogue->getOaiSpec()?>" maxlength="50" size="50" onchange="setFlagMaj(true)"></td>
					</tr>
		  </table>    
    </fieldset>
   <?php } ?>

		<fieldset>
			<legend><?php echo $this->traduire('Critères généraux'); ?> </legend>
				<table border="0" cellpadding="5" cellspacing="0">
					
					<tr>
						<td class="droite" valign="top" style="width:180px;"><?php echo $this->traduire('Types de documents'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("type_doc","type_doc",$this->catalogue->getTypeDoc()); ?></td>
					</tr>
					
					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire('Genres'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("genre","genre",$this->catalogue->getGenre()); ?></td>
					</tr>
					
					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire('Langues'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("langue","langue",$this->catalogue->getLangue()); ?></td>
					</tr>
					
					<tr>
						<td class="droite"><?php echo $this->traduire('Année de parution - depuis'); ?></td>
						<td class="gauche"><input type="text" name="annee_debut" size="4" maxlength="4" value="<?php echo $this->catalogue->getAnneeDebut()?>">&nbsp;(sur 4 chiffres)</td>
					</tr>
					
					<tr>
						<td class="droite"><?php echo $this->traduire('jusqu\'à'); ?></td>
						<td class="gauche"><input type="text" name="annee_fin" size="4" maxlength="4"	 value="<?php echo $this->catalogue->getAnneeFin()?>">&nbsp;(sur 4 chiffres)</td>
					</tr>

					<tr>
						<td class="droite"><?php echo $this->traduire('Cote - depuis'); ?></td>
						<td class="gauche"><input type="text" name="cote_debut" size="25" maxlength="25" value="<?php echo $this->catalogue->getCoteDebut()?>">&nbsp;(Pergame et Nanook uniquement)</td>
					</tr>

					<tr>
						<td class="droite"><?php echo $this->traduire('jusqu\'à'); ?></td>
						<td class="gauche"><input type="text" name="cote_fin" size="25" maxlength="25"	value="<?php echo $this->catalogue->getCoteFin()?>">&nbsp;(Pergame et Nanook uniquement)</td>
					</tr>
					<tr>
						<td class="droite"><?php echo $this->traduire('Nouveautés uniquement'); ?></td>
						<td class="gauche"><input type="checkbox" name="nouveaute"	value="1" <?php if($this->catalogue->getNouveaute()) echo "checked=ckecked"?>></td>
					</tr>
					
				</table>
		</fieldset>

		<fieldset>
			<legend><?php echo $this->traduire('Localisations'); ?> </legend>
				<table border="0" cellpadding="5" cellspacing="0">
					<tr>
						<td class="droite" style="width:150px" valign="top"><?php echo $this->traduire('Bibliothèques'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("bibliotheque","bibliotheque",$this->catalogue->getBibliotheque()); ?></td>
					</tr>

					<tr>
						<td class="droite" style="width:150px" valign="top"><?php echo $this->traduire('Sections'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("section","section",$this->catalogue->getSection()); ?></td>
					</tr>

					<tr>
						<td class="droite" style="width:150px" valign="top"><?php echo $this->traduire('Sites'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("annexe","annexe",$this->catalogue->getAnnexe()); ?></td>
					</tr>

					<tr>
						<td class="droite" style="width:150px" valign="top"><?php echo $this->traduire('Emplacements'); ?></td>
						<td class="gauche"><?php echo $this->TagListeCoches("emplacement","emplacement",$this->catalogue->getEmplacement()); ?></td>
					</tr>

				</table>
		</fieldset>

		<fieldset>
			<legend><?php echo $this->traduire('Critères d\'indexation'); ?> </legend>
				<table border="0" cellpadding="5" cellspacing="0">

					<tr>
						<td colspan="2" class="info">Les critères ci-dessous se cumulent entre eux (opérateur logique "ou"). La dewey et la pcdm4 incluent automatiquement tous leurs sous-indices. Les mots matières incluent toutes les sous-vedettes du mot choisi.</td>
					</tr>

					<tr>
						<td class="droite" valign="top" style="width:130px"><?php echo $this->traduire('Auteurs'); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("auteur","auteur",$this->catalogue->getAuteur()); ?></td>
					</tr>

					<tr>
						<td class="droite" valign="top" style="width:130px"><?php echo $this->traduire('Matières / sujets'); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("matiere","matiere",$this->catalogue->getMatiere()); ?></td>
					</tr>
					
					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire('Indices Dewey'); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("dewey","dewey",$this->catalogue->getDewey()); ?></td>
					</tr>
					
					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire('Pcdm4'); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("pcdm4","pcdm4",$this->catalogue->getPcdm4()); ?></td>
					</tr>

					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire("Centres d'intérêt"); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("interet","interet",$this->catalogue->getInteret()); ?></td>
					</tr>
					
					<tr>
						<td class="droite" valign="top"><?php echo $this->traduire('Tags utilisateur'); ?></td>
						<td class="gauche"><?php echo $this->TagListeSuggestion("tag","tags",$this->catalogue->getTags()); ?></td>
					</tr>
					
				</table>
		</fieldset>
		
		<table>
			<tr>
				<td align="right" style="padding-right:5px;"><?php echo $this->bouton('type=V',"javascript=;setFlagMaj(false);"); ?></td>
				<td align="left" style="padding-left:5px;"> <?php echo $this->bouton('id=29','picto=del.gif','texte=Annuler','url='.BASE_URL.'/admin/catalogue','largeur=120px'); ?></td>
			</tr>
		</table>
	</form>
</div>
</center>
