<?php 
if($this->authUser->ROLE_LEVEL > 6) echo '<p style="font-weight:bold; font-size: 0.9em">'.$this->requete.'</p>';
if(!$this->notices) echo '<p align="center" class="error">Ce catalogue ne renvoie aucun résultat.</p>';
else {
	echo $this->ligneInfos("Notices trouvées",$this->nb_notices);
	echo $this->ligneInfos("Avec vignettes en cache",$this->avec_vignettes);
	echo $this->ligneInfos("Temps d'éxécution de la requête",$this->temps_execution);
}

if($this->notices)
{
	
?>
	<br>
	<table cellspacing="0" cellpadding="0">
		<tr class="soustitre">
			<td style="width:2%;">&nbsp;</td>
			<td style="width:60%">Titre</td>
			<td style="width:38%">Auteur</td>
		</tr>
		<tr><td colspan="6"  class="separ"></td></tr>
<?php	
	$ligne = 0;
	foreach ($this->notices as $notice)
	{
		$ligne ++ ; if ($ligne & 1) $class="first"; else $class="second";
		echo '<tr class="'.$class.'">
						<td align="center" style="padding:3px 5px 3px 0px">'.$this->iconeSupport($notice->getTypeDoc()).'</td>
						<td>'.$notice->getTitrePrincipal().'</td>
						<td>'.$notice->getAuteurPrincipal().'</td>
   				</tr>';
  }
  echo '<tr><td colspan="6"  class="separ"></td></tr>';
	echo '</table>';
	echo '<p style="margin-top:1px;"><small>nb : Affichage des 20 premières notices uniquement...</small></p> ';
}

?>
<br>
<a href="<?php echo BASE_URL."/admin/catalogue/edit?id_catalogue=".$this->id_catalogue; ?>">&raquo;&nbsp;Modifier la définition du catalogue</a>
