<?php
echo $this->tagModelTable($this->suggestions, 
													
													[$this->_('Date'), $this->_('Titre'), $this->_('Auteur'), $this->_('N° abonné')],

													['date_creation', 'titre', 'auteur', 'idabon'],

													[ ['action' => 'edit', 'content' => $this->boutonIco('type=edit')],
														['action' => 'delete', 'content' => $this->boutonIco('type=del')] ],

													'suggestions');
?>