ALTER TABLE `multimedia_location` 
			ADD COLUMN `hold_delay_min` INT(11) UNSIGNED NOT NULL DEFAULT 0, 
			ADD COLUMN `hold_delay_max` INT(11) UNSIGNED NOT NULL DEFAULT 30, 
			ADD COLUMN `auth_delay` INT(11) UNSIGNED NOT NULL DEFAULT 5,
			ADD COLUMN `autohold` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
			ADD COLUMN `autohold_slots_max` INT(11) UNSIGNED NOT NULL DEFAULT 1;
