ALTER TABLE `multimedia_location` 
	ADD COLUMN `days` VARCHAR(255) NOT NULL DEFAULT '',
	ADD COLUMN `open_hour` VARCHAR(255) NOT NULL DEFAULT '08:00', 
	ADD COLUMN `close_hour` VARCHAR(255) NOT NULL DEFAULT '17:30';
