ALTER TABLE  `notices_paniers` DROP PRIMARY KEY;
ALTER TABLE  `notices_paniers` ADD UNIQUE  `USER_PANIER` (  `ID_USER` ,  `ID_PANIER` );
ALTER TABLE  `notices_paniers` ADD  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
