ALTER TABLE `notices` ADD `clef_oeuvre` VARCHAR( 200 ) NOT NULL AFTER `clef_alpha` ;
ALTER TABLE `notices` ADD INDEX ( `clef_oeuvre` ) ;
ALTER TABLE `notices_avis` ADD `CLEF_OEUVRE` VARCHAR( 200 ) NOT NULL AFTER `ID_USER` ;
ALTER TABLE `notices_avis` ADD INDEX ( `CLEF_OEUVRE` ) ;
ALTER TABLE `notices_avis` DROP PRIMARY KEY ;
ALTER TABLE `notices_avis` DROP INDEX `ID_NOTICE`;
ALTER TABLE `notices_avis` ADD `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;
ALTER TABLE `notices_avis` ADD INDEX ( `ID_USER` );
ALTER TABLE `prets` CHANGE `ETIQUETTE` `CODE_BARRES` VARCHAR( 20 ) NOT NULL;